### ISSUE TITLE
View Data within a CausalFrame similar to a DataFrame

### ISSUE THREAD

**Issue by Tanmay-Kulkarni101** [inovex/justcause#27]
Is there any way to look at all the data at the same time similar to that of a ```DataFrame```. If we try to see to see the value in a single replication we see the following error:
```
Python 3.7.5 (default, Nov  7 2019, 10:50:52)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from justcause.data.sets import load_ihdp
>>> rep = load_ihdp(select_rep=[0])[0]
>>> rep
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tanmay/model_env/lib/python3.7/site-packages/pandas/core/frame.py", line 687, in __repr__
    show_dimensions=show_dimensions,
  File "/home/tanmay/model_env/lib/python3.7/site-packages/pandas/core/frame.py", line 818, in to_string
    line_width=line_width,
  File "/home/tanmay/model_env/lib/python3.7/site-packages/pandas/io/formats/format.py", line 614, in __init__
    self._chk_truncate()
  File "/home/tanmay/model_env/lib/python3.7/site-packages/pandas/io/formats/format.py", line 700, in _chk_truncate
    frame = concat((frame.iloc[:row_num, :], frame.iloc[-row_num:, :]))
  File "/home/tanmay/model_env/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 284, in concat
    return op.get_result()
  File "/home/tanmay/model_env/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 503, in get_result
    return cons._from_axes(new_data, self.new_axes).__finalize__(
AttributeError: 'functools.partial' object has no attribute '_from_axes'
```

On creating my own CausalFrame

![image](https://user-images.githubusercontent.com/17275495/76060823-306fd000-5fa8-11ea-9af0-27f793b485bb.png)

It shows all the data in the ```CausaFrame```.  What is the expected behavior? Can the expected behavior be similar to that of a ```DataFrame```?

**Comment by FlorianWilhelm** [comment]
Hi @Tanmay-Kulkarni101, a CausalFrame is just a DataFrame with the described additional functionality, so you can expect in that regard the same behavior. 

Also for me it perfectly works:
![image](https://user-images.githubusercontent.com/3184072/76139971-f4934400-6055-11ea-9fff-e74ff28c29ab.png)

I would assume it has something to do with your Pandas or maybe pyarrow version? I am using Pandas 0.25.2 and pyarrow 0.14.1 right now. As you can see from your stacktrace, the error happens deeply within the pandas code, so I really don't think it's related to justcause. Rather from the fact that the actual data came from a parquet file maybe and something was read in. 
So you cannot work with any of the data sets we provide? Does this error happen for all of them?

**Comment by Tanmay-Kulkarni101** [comment]
I created two fresh environments to reproduce the errors. I tried to run it on both Python 3.6 and Python 3.7. However, I got the same result for IHDP.

For Python 3.6
```
(test_36) tanmay@T-TAKULK-AIO:~$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from justcause.data.sets import load_ihdp
>>> rep = load_ihdp(select_rep=[0])[0]
>>> rep
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tanmay/test_36/lib/python3.6/site-packages/pandas/core/frame.py", line 687, in __repr__
    show_dimensions=show_dimensions,
  File "/home/tanmay/test_36/lib/python3.6/site-packages/pandas/core/frame.py", line 818, in to_string
    line_width=line_width,
  File "/home/tanmay/test_36/lib/python3.6/site-packages/pandas/io/formats/format.py", line 614, in __init__
    self._chk_truncate()
  File "/home/tanmay/test_36/lib/python3.6/site-packages/pandas/io/formats/format.py", line 700, in _chk_truncate
    frame = concat((frame.iloc[:row_num, :], frame.iloc[-row_num:, :]))
  File "/home/tanmay/test_36/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 284, in concat
    return op.get_result()
  File "/home/tanmay/test_36/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 503, in get_result
    return cons._from_axes(new_data, self.new_axes).__finalize__(
AttributeError: 'functools.partial' object has no attribute '_from_axes'
```
For Python 3.7
```
(test_37) tanmay@T-TAKULK-AIO:~$ python3
Python 3.7.5 (default, Nov  7 2019, 10:50:52)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from justcause.data.sets import load_ihdp
>>> rep = load_ihdp(select_rep=[0])[0]
>>> rep
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tanmay/test_37/lib/python3.7/site-packages/pandas/core/frame.py", line 687, in __repr__
    show_dimensions=show_dimensions,
  File "/home/tanmay/test_37/lib/python3.7/site-packages/pandas/core/frame.py", line 818, in to_string
    line_width=line_width,
  File "/home/tanmay/test_37/lib/python3.7/site-packages/pandas/io/formats/format.py", line 614, in __init__
    self._chk_truncate()
  File "/home/tanmay/test_37/lib/python3.7/site-packages/pandas/io/formats/format.py", line 700, in _chk_truncate
    frame = concat((frame.iloc[:row_num, :], frame.iloc[-row_num:, :]))
  File "/home/tanmay/test_37/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 284, in concat
    return op.get_result()
  File "/home/tanmay/test_37/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 503, in get_result
    return cons._from_axes(new_data, self.new_axes).__finalize__(
AttributeError: 'functools.partial' object has no attribute '_from_axes'
```
Packages installed in Python 3.6
```
(test_36) tanmay@T-TAKULK-AIO:~$ pip list --format=columns
Package              Version
-------------------- ------------
absl-py              0.9.0
astor                0.8.1
attrs                19.3.0
causalml             0.7.0
certifi              2019.11.28
cffi                 1.14.0
chardet              3.0.4
cycler               0.10.0
Cython               0.29.15
dill                 0.3.1.1
future               0.18.2
gast                 0.3.3
google-pasta         0.1.8
grpcio               1.27.2
h5py                 2.10.0
idna                 2.9
importlib-metadata   1.5.0
Jinja2               2.11.1
joblib               0.14.1
JustCause            0.3.2
Keras                2.3.1
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.0
kiwisolver           1.1.0
lightgbm             2.3.1
Markdown             3.2.1
MarkupSafe           1.1.1
matplotlib           3.2.0
more-itertools       8.2.0
numpy                1.18.1
packaging            20.3
pandas               1.0.1
patsy                0.5.1
pip                  20.0.2
pkg-resources        0.0.0
pluggy               0.13.1
progressbar2         3.50.0
protobuf             3.11.3
py                   1.8.1
pyarrow              0.16.0
pycparser            2.20
pydotplus            2.0.2
pygam                0.8.0
pyparsing            2.4.6
pytest               5.3.5
python-dateutil      2.8.1
python-utils         2.4.0
pytz                 2019.3
PyYAML               5.3
requests             2.23.0
rpy2                 3.2.6
scikit-learn         0.22.2.post1
scipy                1.4.1
seaborn              0.10.0
setuptools           46.0.0
shap                 0.35.0
simplegeneric        0.8.1
six                  1.14.0
statsmodels          0.11.1
tensorboard          1.14.0
tensorflow           1.14.0
tensorflow-estimator 1.14.0
termcolor            1.1.0
tqdm                 4.43.0
tzlocal              2.0.0
urllib3              1.25.8
wcwidth              0.1.8
Werkzeug             1.0.0
wheel                0.34.2
wrapt                1.12.1
xgboost              1.0.2
zipp                 3.1.0
```
Packages installed in Python 3.7
```
(test_37) tanmay@T-TAKULK-AIO:~$ pip list --format=columns
Package              Version
-------------------- ------------
absl-py              0.9.0
astor                0.8.1
attrs                19.3.0
causalml             0.7.0
certifi              2019.11.28
cffi                 1.14.0
chardet              3.0.4
cycler               0.10.0
Cython               0.29.15
dill                 0.3.1.1
future               0.18.2
gast                 0.3.3
google-pasta         0.1.8
grpcio               1.27.2
h5py                 2.10.0
idna                 2.9
importlib-metadata   1.5.0
Jinja2               2.11.1
joblib               0.14.1
JustCause            0.3.2
Keras                2.3.1
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.0
kiwisolver           1.1.0
lightgbm             2.3.1
Markdown             3.2.1
MarkupSafe           1.1.1
matplotlib           3.2.0
more-itertools       8.2.0
numpy                1.18.1
packaging            20.3
pandas               1.0.1
patsy                0.5.1
pip                  20.0.2
pkg-resources        0.0.0
pluggy               0.13.1
progressbar2         3.50.0
protobuf             3.11.3
py                   1.8.1
pyarrow              0.16.0
pycparser            2.20
pydotplus            2.0.2
pygam                0.8.0
pyparsing            2.4.6
pytest               5.3.5
python-dateutil      2.8.1
python-utils         2.4.0
pytz                 2019.3
PyYAML               5.3
requests             2.23.0
rpy2                 3.2.6
scikit-learn         0.22.2.post1
scipy                1.4.1
seaborn              0.10.0
setuptools           46.0.0
shap                 0.35.0
simplegeneric        0.8.1
six                  1.14.0
statsmodels          0.11.1
tensorboard          1.14.0
tensorflow           1.14.0
tensorflow-estimator 1.14.0
termcolor            1.1.0
tqdm                 4.43.0
tzlocal              2.0.0
urllib3              1.25.8
wcwidth              0.1.8
Werkzeug             1.0.0
wheel                0.34.2
wrapt                1.12.1
xgboost              1.0.2
zipp                 3.1.0
```
Thanks for helping me out.

**Comment by Tanmay-Kulkarni101** [comment]
I also tried the same with the Twins dataset. I got the same error.

For Python 3.6
```
(test_36) tanmay@T-TAKULK-AIO:~$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from justcause.data.sets import load_twins
>>> data = load_twins()
>>> data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tanmay/test_36/lib/python3.6/site-packages/pandas/core/frame.py", line 687, in __repr__
    show_dimensions=show_dimensions,
  File "/home/tanmay/test_36/lib/python3.6/site-packages/pandas/core/frame.py", line 818, in to_string
    line_width=line_width,
  File "/home/tanmay/test_36/lib/python3.6/site-packages/pandas/io/formats/format.py", line 614, in __init__
    self._chk_truncate()
  File "/home/tanmay/test_36/lib/python3.6/site-packages/pandas/io/formats/format.py", line 700, in _chk_truncate
    frame = concat((frame.iloc[:row_num, :], frame.iloc[-row_num:, :]))
  File "/home/tanmay/test_36/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 284, in concat
    return op.get_result()
  File "/home/tanmay/test_36/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 503, in get_result
    return cons._from_axes(new_data, self.new_axes).__finalize__(
AttributeError: 'functools.partial' object has no attribute '_from_axes'
```

For Python 3.7
```
(test_37) tanmay@T-TAKULK-AIO:~$ python3
Python 3.7.5 (default, Nov  7 2019, 10:50:52)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from justcause.data.sets import load_twins
>>> data = load_twins()
>>> data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tanmay/test_37/lib/python3.7/site-packages/pandas/core/frame.py", line 687, in __repr__
    show_dimensions=show_dimensions,
  File "/home/tanmay/test_37/lib/python3.7/site-packages/pandas/core/frame.py", line 818, in to_string
    line_width=line_width,
  File "/home/tanmay/test_37/lib/python3.7/site-packages/pandas/io/formats/format.py", line 614, in __init__
    self._chk_truncate()
  File "/home/tanmay/test_37/lib/python3.7/site-packages/pandas/io/formats/format.py", line 700, in _chk_truncate
    frame = concat((frame.iloc[:row_num, :], frame.iloc[-row_num:, :]))
  File "/home/tanmay/test_37/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 284, in concat
    return op.get_result()
  File "/home/tanmay/test_37/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 503, in get_result
    return cons._from_axes(new_data, self.new_axes).__finalize__(
AttributeError: 'functools.partial' object has no attribute '_from_axes'
```
The issue seems to be the same in both the IHDP and twins.

**Comment by FlorianWilhelm** [comment]
Could you try the current version on master? I removed some functionality. 
causalml is a just to fast-moving target to keep supporting it as well as everything that depends on Tensorflow. My idea would be to focus JustCause more on the evaluation and data provider part. This will also make the installation a lot easier. What do you think @MaximilianFranz?

**Comment by MaximilianFranz** [comment]
Bold move, but makes total sense!

**Comment by Tanmay-Kulkarni101** [comment]
I build your package from source, it seems to be working now. I still am not sure what went wrong. Nice work guys.
![image](https://user-images.githubusercontent.com/17275495/77051163-e0096100-69f0-11ea-8bf6-529cb4f25681.png)
