### ISSUE TITLE
Missing Requests module in dependenicies

### ISSUE THREAD

**Issue by Tanmay-Kulkarni101** [inovex/justcause#28]
I created a new virtual environment in both Python 3.6 and Python 3.7.  On attempting to load the IHDP datasets. It gives the error that the requests module is missing.

For Python 3.6
```
(test_36) tanmay@T-TAKULK-AIO:~$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from justcause.data.sets import load_ihdp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tanmay/test_36/lib/python3.6/site-packages/justcause/__init__.py", line 4, in <module>
    from . import data
  File "/home/tanmay/test_36/lib/python3.6/site-packages/justcause/data/__init__.py", line 14, in <module>
    from . import sets
  File "/home/tanmay/test_36/lib/python3.6/site-packages/justcause/data/sets/__init__.py", line 24, in <module>
    from .ibm import load_ibm
  File "/home/tanmay/test_36/lib/python3.6/site-packages/justcause/data/sets/ibm.py", line 24, in <module>
    from ..transport import get_covariates_df, get_outcomes_df
  File "/home/tanmay/test_36/lib/python3.6/site-packages/justcause/data/transport.py", line 18, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```
For Python 3.7
```
(test_37) tanmay@T-TAKULK-AIO:~$ python3
Python 3.7.5 (default, Nov  7 2019, 10:50:52)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from justcause.data.sets import load_ihdp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tanmay/test_37/lib/python3.7/site-packages/justcause/__init__.py", line 4, in <module>
    from . import data
  File "/home/tanmay/test_37/lib/python3.7/site-packages/justcause/data/__init__.py", line 14, in <module>
    from . import sets
  File "/home/tanmay/test_37/lib/python3.7/site-packages/justcause/data/sets/__init__.py", line 24, in <module>
    from .ibm import load_ibm
  File "/home/tanmay/test_37/lib/python3.7/site-packages/justcause/data/sets/ibm.py", line 24, in <module>
    from ..transport import get_covariates_df, get_outcomes_df
  File "/home/tanmay/test_37/lib/python3.7/site-packages/justcause/data/transport.py", line 18, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```
It can be solved easily by installing with ``pip3``

``` pip3 install requests```

Can you add it to the dependency list, so that we don't have to install manually every time.

**Comment by FlorianWilhelm** [comment]
Thanks, good point, this was missing I'll add it. Done in fd3fd9d8a92e0cfd5021ec2e667bcb0d4ee12c31.
